pull request for docs addition
sylvainmouquet/reattempt pull request #40
Opened 2024-12-17 08:11 UTC by SigireddyBalasai

added docs to current code with mkdocs

2024-12-19 08:39 UTC, sylvainmouquet requested changes

2024-12-19 08:39 UTC, sylvainmouquet commented on reattempt/__init__.py
> +            if attempt == max_retries and capture_exception:
this change is not valid

2024-12-19 08:39 UTC, sylvainmouquet commented on reattempt/__init__.py
> -                        # https://docs.python.org/3/library/contextlib.html#contextlib.aclosing
it's better to keep the documentation

2024-12-24 17:55 UTC, SigireddyBalasai reviewed
done

2025-05-08 14:20 UTC, closed without merging